name: Deploy Hands-on Resources

on:
  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Resource Group Name'
        required: true
        default: 'rg-cloudworkshop'

# Require write permission to Fetch an OIDC token.
permissions:
  id-token: write
  contents: read

jobs:
  deploy-storage_and_upload-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Create an Azure storage account
        id: create_storage_account
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ github.event.inputs.resourceGroup }}
          template: ./bicep/modules/storageaccount.bicep
          parameters: ./bicep/parameters/storageaccount.bicepparam
      
      - name: Upload files to Azure storage account
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ steps.create_storage_account.outputs.storageAccountName }} --destination ${{ steps.create_storage_account.outputs.containerName }} --source ./contents
